"""Регионы, загружаемые в БД"""
region = {
    '01': 'Adygeja_Resp',
    '04': 'Altaj_Resp',
    '22': 'Altajskij_kraj',
    '28': 'Amurskaja_obl',
    '29': 'Arkhangelskaja_obl',
    '30': 'Astrakhanskaja_obl',
    '94': 'Bajkonur_g',
    '02': 'Bashkortostan_Resp',
    '31': 'Belgorodskaja_obl',
    '32': 'Brjanskaja_obl',
    '03': 'Burjatija_Resp',
    '20': 'Chechenskaja_Resp',
    '74': 'Cheljabinskaja_obl',
    '87': 'Chukotskij_AO',
    '21': 'Chuvashskaja_Resp',
    '05': 'Dagestan_Resp',
    '79': 'Evrejskaja_Aobl',
    '06': 'Ingushetija_Resp',
    '38': 'Irkutskaja_obl',
    '37': 'Ivanovskaja_obl',
    '89': 'Jamalo-Neneckij_AO',
    '76': 'Jaroslavskaja_obl',
    '07': 'Kabardino-Balkarskaja_Resp',
    '39': 'Kaliningradskaja_obl',
    '08': 'Kalmykija_Resp',
    '40': 'Kaluzhskaja_obl',
    '41': 'Kamchatskij_kraj',
    '82': 'Kamchatskij_kraj',
    '09': 'Karachaevo-Cherkesskaja_Resp',
    '10': 'Karelija_Resp',
    '42': 'Kemerovskaja_obl',
    '27': 'Khabarovskij_kraj',
    '19': 'Khakasija_Resp',
    '86': 'Khanty-Mansijskij_AO-Jugra_AO',
    '43': 'Kirovskaja_obl',
    '11': 'Komi_Resp',
    '44': 'Kostromskaja_obl',
    '23': 'Krasnodarskij_kraj',
    '24': 'Krasnojarskij_kraj',
    '91': 'Krim_Resp',
    '45': 'Kurganskaja_obl',
    '46': 'Kurskaja_obl',
    '47': 'Leningradskaja_obl',
    '48': 'Lipeckaja_obl',
    '49': 'Magadanskaja_obl',
    '12': 'Marij_El_Resp',
    '13': 'Mordovija_Resp',
    '50': 'Moskovskaja_obl',
    '77': 'Moskva',
    '51': 'Murmanskaja_obl',
    '83': 'Neneckij_AO',
    '52': 'Nizhegorodskaja_obl',
    '53': 'Novgorodskaja_obl',
    '54': 'Novosibirskaja_obl',
    '55': 'Omskaja_obl',
    '56': 'Orenburgskaja_obl',
    '57': 'Orlovskaja_obl',
    '58': 'Penzenskaja_obl',
    '59': 'Permskij_kraj',
    '25': 'Primorskij_kraj',
    '60': 'Pskovskaja_obl',
    '62': 'Rjazanskaja_obl',
    '61': 'Rostovskaja_obl',
    '14': 'Sakha_Jakutija_Resp',
    '65': 'Sakhalinskaja_obl',
    '63': 'Samarskaja_obl',
    '78': 'Sankt-Peterburg',
    '64': 'Saratovskaja_obl',
    '92': 'Sevastopol_g',
    '15': 'Severnaja_Osetija-Alanija_Resp',
    '67': 'Smolenskaja_obl',
    '26': 'Stavropolskij_kraj',
    '66': 'Sverdlovskaja_obl',
    '68': 'Tambovskaja_obl',
    '16': 'Tatarstan_Resp',
    '72': 'Tjumenskaja_obl',
    '70': 'Tomskaja_obl',
    '71': 'Tulskaja_obl',
    '69': 'Tverskaja_obl',
    '17': 'Tyva_Resp',
    '18': 'Udmurtskaja_Resp',
    '73': 'Uljanovskaja_obl',
    '33': 'Vladimirskaja_obl',
    '34': 'Volgogradskaja_obl',
    '35': 'Vologodskaja_obl',
    '36': 'Voronezhskaja_obl',
    '75': 'Zabajkalskij_kraj'
}  # Список регионов
region_names = {
    'Adygeja_Resp': '01',
    'Altaj_Resp': '04',
    'Altajskij_kraj': '22',
    'Amurskaja_obl': '28',
    'Arkhangelskaja_obl': '29',
    'Astrakhanskaja_obl': '30',
    'Bajkonur_g': '94',
    'Bashkortostan_Resp': '02',
    'Belgorodskaja_obl': '31',
    'Brjanskaja_obl': '32',
    'Burjatija_Resp': '03',
    'Chechenskaja_Resp': '20',
    'Cheljabinskaja_obl': '74',
    'Chukotskij_AO': '87',
    'Chuvashskaja_Resp': '21',
    'Dagestan_Resp': '05',
    'Evrejskaja_Aobl': '79',
    'Ingushetija_Resp': '06',
    'Irkutskaja_obl': '38',
    'Ivanovskaja_obl': '37',
    'Jamalo-Neneckij_AO': '89',
    'Jaroslavskaja_obl': '76',
    'Kabardino-Balkarskaja_Resp': '07',
    'Kaliningradskaja_obl': '39',
    'Kalmykija_Resp': '08',
    'Kaluzhskaja_obl': '40',
    'Kamchatskij_kraj': '82',
    'Karachaevo-Cherkesskaja_Resp': '09',
    'Karelija_Resp': '10',
    'Kemerovskaja_obl': '42',
    'Khabarovskij_kraj': '27',
    'Khakasija_Resp': '19',
    'Khanty-Mansijskij_AO-Jugra_AO': '86',
    'Kirovskaja_obl': '43',
    'Komi_Resp': '11',
    'Kostromskaja_obl': '44',
    'Krasnodarskij_kraj': '23',
    'Krasnojarskij_kraj': '24',
    'Krim_Resp': '91',
    'Kurganskaja_obl': '45',
    'Kurskaja_obl': '46',
    'Leningradskaja_obl': '47',
    'Lipeckaja_obl': '48',
    'Magadanskaja_obl': '49',
    'Marij_El_Resp': '12',
    'Mordovija_Resp': '13',
    'Moskovskaja_obl': '50',
    'Moskva': '77',
    'Murmanskaja_obl': '51',
    'Neneckij_AO': '83',
    'Nizhegorodskaja_obl': '52',
    'Novgorodskaja_obl': '53',
    'Novosibirskaja_obl': '54',
    'Omskaja_obl': '55',
    'Orenburgskaja_obl': '56',
    'Orlovskaja_obl': '57',
    'Penzenskaja_obl': '58',
    'Permskij_kraj': '59',
    'Primorskij_kraj': '25',
    'Pskovskaja_obl': '60',
    'Rjazanskaja_obl': '62',
    'Rostovskaja_obl': '61',
    'Sakha_Jakutija_Resp': '14',
    'Sakhalinskaja_obl': '65',
    'Samarskaja_obl': '63',
    'Sankt-Peterburg': '78',
    'Saratovskaja_obl': '64',
    'Sevastopol_g': '92',
    'Severnaja_Osetija-Alanija_Resp': '15',
    'Smolenskaja_obl': '67',
    'Stavropolskij_kraj': '26',
    'Sverdlovskaja_obl': '66',
    'Tambovskaja_obl': '68',
    'Tatarstan_Resp': '16',
    'Tjumenskaja_obl': '72',
    'Tomskaja_obl': '70',
    'Tulskaja_obl': '71',
    'Tverskaja_obl': '69',
    'Tyva_Resp': '17',
    'Udmurtskaja_Resp': '18',
    'Uljanovskaja_obl': '73',
    'Vladimirskaja_obl': '33',
    'Volgogradskaja_obl': '34',
    'Vologodskaja_obl': '35',
    'Voronezhskaja_obl': '36',
    'Zabajkalskij_kraj': '75'}
northwestern_fd = {'78', '47', '53', '60', '10', '29', '11', '35', '51', '83', '39'}             # Северо-западный ФО
central_fd = {'77', '32', '33', '37', '40', '44', '50', '57', '62', '67', '69', '71', '76', '31', '36', '46', '48',
              '68'}                                                                             # Центральный ФО
volga_fd = {'52', '43', '12', '13', '21', '58', '73', '64', '63', '56', '02', '16', '18', '59'}  # Приволжский ФО
southern_fd = {'08', '34', '30', '01', '61', '23'}                                               # Южный ФО
north_caucasian_fd = {'26', '15', '09', '07', '20', '06', '05'}                                  # Северо-Кавказский ФО
ural_fd = {'66', '74', '45', '72', '89', '86'}                                                   # Уральский ФО
siberian_fd = {'04', '22', '54', '70', '42', '55', '19', '17', '24', '38', '03', '75'}           # Сибирский ФО
far_eastern_fd = {'14', '79', '87', '25', '27', '28', '41', '49', '65'}                          # Дальневосточный ФО
crimean_fd = {'94', '91', '92'}                                                                  # Крымский ФО
all_regions = northwestern_fd | central_fd | volga_fd | southern_fd | north_caucasian_fd | ural_fd | siberian_fd | \
              far_eastern_fd | crimean_fd

config = {
        'user': 'root1',
        'password': '94b10644b610480e9ef334779068602df3824b11fd7d3261',
        'host': '134.0.115.33',
        'database': 'contracts_new',
        'raise_on_warnings': True
    }       # Данные для подключения к БД
# config = {
#         'user': 'root',
#         'password': 'root',
#         'host': 'localhost',
#         'database': 'contracts',
#         'raise_on_warnings': True
#     }       # Данные для подключения к БД
field_links = {
    'id': 'id',
    'regNum': 'regNum',
    'publishDate': 'publish_date',
    'printFormurl': 'Печатная_форма_кнтркта',
    'region': 'Регион',
    'currentContractStage': 'Текущее_состояние_кнтркта',
    'number': 'Номер_кнтркта',
    'versionNumber': 'Номер_изменения',
    'attachmentsattachmentdocDescription': 'Прикрепленный_док_Описание',
    'attachmentsattachmentfileName': 'Прикрепленный_док_Назв',
    'attachmentsattachmenturl': 'Прикрепленный_док_Ссылка',
    'contractSubject': 'Предмет_кнтркта',
    'customercustomerAccountsDetailscustomerAccountDetailsaccountType': 'Рекв_счета_заказчика_Тип_счета',
    'customercustomerAccountsDetailscustomerAccountDetailsbankAccountNumber': 'Рекв_счета_заказчика_Номер_счета',
    'customercustomerAccountsDetailscustomerAccountDetailsbik': 'Рекв_счета_заказчика_БИК_банка',
    'customercustomerAccountsDetailscustomerAccountDetailscorrAccountNumber': 'Рекв_счета_заказчика_Корр_счет',
    'customercustomerAccountsDetailscustomerAccountDetailscreditOrgName': 'Рекв_счета_заказчика_Наим_банка',
    'customerfullName': 'Заказчик_Полное_наим',
    'customerinn': 'Заказчик_ИНН',
    'customerkpp': 'Заказчик_КПП',
    'customerregistrationDate': 'Заказчик_Дата_постановки_на_учет',
    'customershortName': 'Заказчик_Сокращенное_наим',
    'deliveryPlaceInfobyKLADRInfoKLADRInfofullName': 'Место_поставки_Назв',
    'deliveryPlaceInfobyKLADRInfodeliveryPlace': 'Место_поставки_Адрес',
    'documentBase': 'Рекв_дока_подтверждающего_основание_заключ_кнтркта',
    'executionPeriodendDate': 'Дата_окончания_исполнения_кнтркта',
    'executionPeriodstagesendDate': 'Дата_окончания_исполнения_этапа',
    'executionPeriodstagesstageAdvancePaymentSumpriceValue': 'Размер_аванса_по_этапу_кнтркта_в_валют_кнтркта',
    'executionPeriodstagesstageAdvancePaymentSumpriceValueRUR': 'Размер_аванса_по_этапу_кнтркта_в_российских_рублях',
    'executionPeriodstagesstageAdvancePaymentSumsumInPercents': 'Процент_аванса_по_этапу_кнтркта',
    'executionPeriodstagesstagePrice': 'Цена_этапа_кнтркта_в_валют_кнтркта',
    'executionPeriodstagesstagePriceRUR': 'Цена_этапа_кнтркта_в_российских_рублях',
    'executionPeriodstagesstartDate': 'Дата_начала_исполнения_этапа',
    'executionPeriodstartDate': 'Дата_начала_исполнения_кнтркта',
    'executionsexecutionKTRUname': 'Инфо_об_исполн_Имя_по_КТРУ',
    'executionsexecutionMNNInfoMNNName': 'Инфо_об_исполн_Предмет_кнтркта_наим_лекарств_препаратов',
    'executionsexecutionOKEIfullName': 'Инфо_об_исполн_Единица_измерения',
    'executionsexecutionOKPD2name': 'Инфо_об_исполн_Классификация_по_ОКПД2',
    'executionsexecutionattachmentdocDescription': 'Инфо_об_исполн_Прикрепленный_док_Описание',
    'executionsexecutionattachmentfileName': 'Инфо_об_исполн_Прикрепленный_док_Назв',
    'executionsexecutionattachmenturl': 'Инфо_об_исполн_Прикрепленный_док_Ссылка',
    'executionsexecutioncurrencyname': 'Инфо_об_исполн_Валюта',
    'executionsexecutiondocAcceptancedeliveryAcceptDate': 'Инфо_об_исполн_Док_о_приемке_Дата_подписания_заказчиком',
    'executionsexecutiondocAcceptancedocumentDate': 'Инфо_об_исполн_Док_о_приемке_Дата',
    'executionsexecutiondocAcceptancedocumentNum': 'Инфо_об_исполн_Док_о_приемке_Номер',
    'executionsexecutiondocAcceptancefulfilmentSumRUR': 'Инфо_об_исполн_Док_о_приемке_Стоимость_исполненных_обязательств',
    'executionsexecutiondocAcceptancename': 'Инфо_об_исполн_Док_о_приемке_Назв',
    'executionsexecutiondocAcceptancereceiptDocumentsattachmentdocDescription': 'Инфо_об_исполн_Док_подтверждающий_приемку_товара_Описание',
    'executionsexecutiondocAcceptancereceiptDocumentsattachmentfileName': 'Инфо_об_исполн_Док_подтверждающий_приемку_товара_Назв',
    'executionsexecutiondocAcceptancereceiptDocumentsattachmenturl': 'Инфо_об_исполн_Док_подтверждающий_приемку_товара_Ссылка',
    'executionsexecutiondocExecutiondocumentDate': 'Инфо_об_исполн_Док_об_исполн_кнтркта_Дата',
    'executionsexecutiondocExecutiondocumentNum': 'Инфо_об_исполн_Док_об_исполн_кнтркта_Номер',
    'executionsexecutiondocExecutionname': 'Инфо_об_исполн_Док_об_исполн_кнтркта_Назв',
    'executionsexecutionpaid': 'Инфо_об_исполн_Фактически_оплачено_в_валюте_платежа',
    'executionsexecutionpaidRUR': 'Инфо_об_исполн_Фактически_оплачено_в_руб_экв',
    'executionsexecutionpaidVAT': 'Инфо_об_исполн_Значение_НДС_факт_оплач_суммы_в_валюте_платежа',
    'executionsexecutionpaidVATRUR': 'Инфо_об_исполн_Значение_НДС_факт_оплач_суммы_в_руб_экв',
    'executionsexecutionpayDocdocumentDate': 'Инфо_об_исполн_Платежный_док_Дата',
    'executionsexecutionpayDocdocumentName': 'Инфо_об_исполн_Платежный_док_Назв',
    'executionsexecutionpayDocdocumentNum': 'Инфо_об_исполн_Платежный_док_Номер',
    'executionsexecutionproductVATRate': 'Инфо_об_исполн_Объект_закуп_Ставка_НДС',
    'executionsexecutionproductname': 'Инфо_об_исполн_Объект_закуп_Назв',
    'executionsexecutionproductquantity': 'Инфо_об_исполн_Объект_закуп_Колво',
    'executionsexecutionproducttype': 'Инфо_об_исполн_Объект_закуп_Тип',
    'executionsexecutionquantityContractSubjectfulfilledCost': 'Инфо_об_исполн_Инфо_об_обекте_закуп_Стоимость',
    'executionsexecutionquantityContractSubjectindexNum': 'Инфо_об_исполн_Инфо_об_обекте_закуп_Порядковый_номер',
    'executionsexecutionquantityContractSubjectnomenclature': 'Инфо_об_исполн_Инфо_об_обекте_закуп_Описание',
    'executionsexecutionquantityContractSubjectquantity': 'Инфо_об_исполн_Инфо_об_обекте_закуп_Колво',
    'executionsexecutionquantityContractSubjectsquantityContractSubjectKTRUname': 'Инфо_об_исполн_Инфо_об_обекте_закуп_Назв_по_КТРУ',
    'executionsexecutionquantityContractSubjectsquantityContractSubjectOKEIfullName': 'Инфо_об_исполн_Инфо_об_обекте_закуп_Единица_измерения',
    'executionsexecutionquantityContractSubjectsquantityContractSubjectOKPD2name': 'Инфо_об_исполн_Инфо_об_обекте_закуп_Назв_по_ОКПД2',
    'executionsexecutionquantityContractSubjectsquantityContractSubjectfulfilledCost': 'Инфо_об_исполн_Инфо_об_обекте_закуп_Стоимость',
    'executionsexecutionquantityContractSubjectsquantityContractSubjectindexNum': 'Инфо_об_исполн_Инфо_об_обекте_закуп_Порядковый_номер',
    'executionsexecutionquantityContractSubjectsquantityContractSubjectproductKTRUname': 'Инфо_об_исполн_Инфо_об_обекте_закуп_Назв_по_КТРУ',
    'executionsexecutionquantityContractSubjectsquantityContractSubjectproductOKEIfullName': 'Инфо_об_исполн_Инфо_об_обекте_закуп_Единица_измерения',
    'executionsexecutionquantityContractSubjectsquantityContractSubjectproductOKPD2name': 'Инфо_об_исполн_Инфо_об_обекте_закуп_Назв_по_ОКПД2',
    'executionsexecutionquantityContractSubjectsquantityContractSubjectproductVATRate': 'Инфо_об_исполн_Инфо_об_обекте_закуп_Ставка_НДС',
    'executionsexecutionquantityContractSubjectsquantityContractSubjectproducthierarchyType': 'Инфо_об_исполн_Инфо_об_обекте_закуп_Тип_обекта_закуп_в_иерархии',
    'executionsexecutionquantityContractSubjectsquantityContractSubjectproductname': 'Инфо_об_исполн_Инфо_об_обекте_закуп_Назв',
    'executionsexecutionquantityContractSubjectsquantityContractSubjectproductpreviouslySuppliedQuantity': 'Инфо_об_исполн_Инфо_об_обекте_закуп_Объем_ранее_поставленного',
    'executionsexecutionquantityContractSubjectsquantityContractSubjectproducttype': 'Инфо_об_исполн_Инфо_об_обекте_закуп_Тип',
    'executionsexecutionquantityContractSubjectsquantityContractSubjectquantity': 'Инфо_об_исполн_Инфо_об_обекте_закуп_Колво',
    'executionsexecutionquantityContractSubjectsquantityContractSubjectunitPrice': 'Инфо_об_исполн_Инфо_об_обекте_закуп_Цена',
    'executionsexecutionquantityContractSubjectunitPrice': 'Инфо_об_исполн_Инфо_об_обекте_закуп_Цена',
    'executionsexecutionquantityDrugContractSubjectVATRUR': 'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_НДС',
    'executionsexecutionquantityDrugContractSubjectVATRate': 'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Ставка_НДС',
    'executionsexecutionquantityDrugContractSubjectconsumerPackagesQuantity': 'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Колво_упаковок',
    'executionsexecutionquantityDrugContractSubjectdrugSeries': 'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Серия',
    'executionsexecutionquantityDrugContractSubjectexpirationDate': 'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Срок_годности',
    'executionsexecutionquantityDrugContractSubjectfulfilmentCostRUR': 'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Стоимость',
    'executionsexecutionquantityDrugContractSubjectisZNVLP': 'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Стоимость_ЖНВЛП',
    'executionsexecutionquantityDrugContractSubjectpackagePrice': 'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Цена_упаковки',
    'executionsexecutionquantityDrugContractSubjectsquantityDrugContractSubjectMNNInfoMNNName': 'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Наим_МНН',
    'executionsexecutionquantityDrugContractSubjectsquantityDrugContractSubjectOKEIfullName': 'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Единица_измерения',
    'executionsexecutionquantityDrugContractSubjectsquantityDrugContractSubjectOKPD2name': 'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Назв_по_ОКПД2',
    'executionsexecutionquantityDrugContractSubjectsquantityDrugContractSubjectVATRUR': 'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_НДС',
    'executionsexecutionquantityDrugContractSubjectsquantityDrugContractSubjectVATRate': 'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Ставка_НДС',
    'executionsexecutionquantityDrugContractSubjectsquantityDrugContractSubjectconsumerPackagesQuantity': 'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Колво_упаковок',
    'executionsexecutionquantityDrugContractSubjectsquantityDrugContractSubjectdrugProductInfodrugInfoUsingTextFormMNNName': 'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Наим_МНН',
    'executionsexecutionquantityDrugContractSubjectsquantityDrugContractSubjectdrugProductInfodrugInfoUsingTextFormtradeName': 'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Торговое_назв',
    'executionsexecutionquantityDrugContractSubjectsquantityDrugContractSubjectdrugSeries': 'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Серия',
    'executionsexecutionquantityDrugContractSubjectsquantityDrugContractSubjectexpirationDate': 'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Срок_годности',
    'executionsexecutionquantityDrugContractSubjectsquantityDrugContractSubjectfulfilmentCostRUR': 'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Стоимость',
    'executionsexecutionquantityDrugContractSubjectsquantityDrugContractSubjectisZNVLP': 'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Стоимость_ЖНВЛП',
    'executionsexecutionquantityDrugContractSubjectsquantityDrugContractSubjectpackagePrice': 'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Цена_упаковки',
    'executionsexecutionquantityDrugContractSubjectsquantityDrugContractSubjectproductMNNsInfoMNNInfoMNNName': 'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Наим_МНН',
    'executionsexecutionquantityDrugContractSubjectsquantityDrugContractSubjectproductOKEIfullName': 'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Единица_измерения',
    'executionsexecutionquantityDrugContractSubjectsquantityDrugContractSubjectproductOKPD2name': 'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Назв_по_ОКПД2',
    'executionsexecutionquantityDrugContractSubjectsquantityDrugContractSubjectproductname': 'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Назв',
    'executionsexecutionquantityDrugContractSubjectsquantityDrugContractSubjectproductquantity': 'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Колво',
    'executionsexecutionquantityDrugContractSubjectsquantityDrugContractSubjectproducttype': 'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Тип',
    'executionsexecutionquantityDrugContractSubjectsquantityDrugContractSubjecttradeInfotradeName': 'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Торговое_назв',
    'executionsexecutionquantityDrugContractSubjectsumaryDrugQuantity': 'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Колво_поставленного',
    'executionsexecutionreceiptDocumentsattachmentdocDescription': 'Инфо_об_исполн_Док_подтверждающие_приемку_товара_Описание',
    'executionsexecutionreceiptDocumentsattachmentfileName': 'Инфо_об_исполн_Док_подтверждающие_приемку_товара_Назв',
    'executionsexecutionreceiptDocumentsattachmenturl': 'Инфо_об_исполн_Док_подтверждающие_приемку_товара_Ссылка',
    'executionsexecutiontradeInfotradeName': 'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Торговое_назв',
    'executionsordinalNumber': 'Инфо_об_исполн_Номер_исполнения_в_рамках_этапа',
    'executionsstageendDate': 'Инфо_об_исполн_Дата_окончания_исполнения_этапа',
    'foundationfcsOrderordercontractProjectNumber': 'Основан_заключ_кнтркта_Закуп_Реестровый_номер',
    'foundationfcsOrderorderlotNumber': 'Основан_заключ_кнтркта_Закуп_Порядковый_номер_лота',
    'foundationfcsOrderordernotificationNumber': 'Основан_заключ_кнтркта_Закуп_Номер_извещения_о_проведении',
    'foundationfcsOrderorderplacing': 'Основан_заключ_кнтркта_Закуп_Способ_определения_поставщиков',
    'foundationfcsOrderordersingleCustomerattachmentsattachmentdocDescription': 'Основан_заключ_кнтркта_Закуп_у_одного_поставщ_Вложение_Описание',
    'foundationfcsOrderordersingleCustomerattachmentsattachmentfileName': 'Основан_заключ_кнтркта_Закуп_у_одного_поставщ_Вложение_Назв',
    'foundationfcsOrderordersingleCustomerattachmentsattachmenturl': 'Основан_заключ_кнтркта_Закуп_у_одного_поставщ_Вложение_Ссылка',
    'foundationfcsOrderordersingleCustomerdocumentname': 'Основан_заключ_кнтркта_Закуп_у_одного_поставщ_Док',
    'foundationfcsOrderordersingleCustomerreasonname': 'Основан_заключ_кнтркта_Закуп_у_одного_поставщ_Причина',
    'foundationfcsOrdersingleCustomerattachmentsattachmentdocDescription': 'Основан_заключ_кнтркта_Закуп_у_един_поставщ_Вложение_Описание',
    'foundationfcsOrdersingleCustomerattachmentsattachmentfileName': 'Основан_заключ_кнтркта_Закуп_у_един_поставщ_Вложение_Назв',
    'foundationfcsOrdersingleCustomerattachmentsattachmenturl': 'Основан_заключ_кнтркта_Закуп_у_един_поставщ_Вложение_Ссылка',
    'foundationfcsOrdersingleCustomerdocumentname': 'Основан_заключ_кнтркта_Закуп_у_един_поставщ_Док',
    'foundationfcsOrdersingleCustomerreasonname': 'Основан_заключ_кнтркта_Закуп_у_един_поставщ_Причина',
    'href': 'Гиперссылка_на_опубликованные_сведения_о_контракте',
    'paymentDocumentsattachmentdocDescription': 'Док_подтверждающие_исполнение_оплату_Вложение_Описание',
    'paymentDocumentsattachmentfileName': 'Док_подтверждающие_исполнение_оплату_Вложение_Назв',
    'paymentDocumentsattachmenturl': 'Док_подтверждающие_исполнение_оплату_Вложение_Ссылка',
    'penaltiespenaltyAccrualaccrualAmount': 'Инфо_о_неустойках_Начисл_неуст_Размер',
    'penaltiespenaltyAccrualcontractParty': 'Инфо_о_неустойках_Начисл_неуст_Сторона_кнтркта',
    'penaltiespenaltyAccrualcurrencyname': 'Инфо_о_неустойках_Начисл_неуст_Валюта',
    'penaltiespenaltyAccrualpaymentspaymentamount': 'Инфо_о_неустойках_Начисл_неуст_Оплата_Сумма_в_валюте',
    'penaltiespenaltyAccrualpaymentspaymentamountRUR': 'Инфо_о_неустойках_Начисл_неуст_Оплата_Сумма_в_рублях',
    'penaltiespenaltyAccrualpaymentspaymentdocumentDate': 'Инфо_о_неустойках_Начисл_неуст_Докуент_об_оплате_Дата',
    'penaltiespenaltyAccrualpaymentspaymentdocumentName': 'Инфо_о_неустойках_Начисл_неуст_Докуент_об_оплате_Назв',
    'penaltiespenaltyAccrualpaymentspaymentdocumentNum': 'Инфо_о_неустойках_Начисл_неуст_Докуент_об_оплате_Номер',
    'penaltiespenaltyAccrualpaymentstotalAmount': 'Инфо_о_неустойках_Начисл_неуст_Итого_оплачено',
    'penaltiespenaltyAccrualpenaltyDocumentdocumentDate': 'Инфо_о_неустойках_Начисл_неуст_Требование_заказчика_Дата',
    'penaltiespenaltyAccrualpenaltyDocumentdocumentName': 'Инфо_о_неустойках_Начисл_неуст_Требование_заказчика_Назв',
    'penaltiespenaltyAccrualpenaltyDocumentdocumentNum': 'Инфо_о_неустойках_Начисл_неуст_Требование_заказчика_Номер',
    'penaltiespenaltyAccrualpenaltyReasonname': 'Инфо_о_неустойках_Начисл_неуст_Причина',
    'penaltiespenaltyAccrualpenaltyType': 'Инфо_о_неустойках_Начисл_неуст_Тип_взыскания',
    'placementDate': 'Дата_первоначального_размещения_дока',
    'placerresponsibleOrgfullName': 'Организация_разместившая_контракт',
    'placerresponsibleRole': 'Роль_организации_разместившей_контракт',
    'priceInfocurrencyname': 'Инфо_о_цене_кнтркта_Валюта',
    'priceInfoprice': 'Инфо_о_цене_кнтркта_Цена_в_валют_кнтркта',
    'priceInfopriceRUR': 'Инфо_о_цене_кнтркта_Цена_кнтркта_в_руб_экв',
    'priceInfopriceVAT': 'Инфо_о_цене_кнтркта_Значение_НДС_в_валют_кнтркта',
    'priceInfopriceVATRUR': 'Инфо_о_цене_кнтркта_Значение_НДС_в_руб_экв',
    'productsproductKTRUcharacteristicscharacteristicsUsingReferenceInfoname': 'Объекты_закуп_Характеристика_позиции',
    'productsproductKTRUcharacteristicscharacteristicsUsingReferenceInfovalueRangemax': 'Объекты_закуп_Характеристика_позиции_Максимальное_значение',
    'productsproductKTRUcharacteristicscharacteristicsUsingReferenceInfovalueRangemin': 'Объекты_закуп_Характеристика_позиции_Минимальное_значение',
    'productsproductKTRUcharacteristicscharacteristicsUsingReferenceInfovalueSetconcreteValue': 'Объекты_закуп_Характеристика_позиции_Значение',
    'productsproductKTRUcharacteristicscharacteristicsUsingReferenceInfovaluequalityDescription': 'Объекты_закуп_Характеристика_позиции_Описание',
    'productsproductKTRUcharacteristicscharacteristicsUsingReferenceInfovaluesvaluequalityDescription': 'Объекты_закуп_Характеристика_позиции_Описание',
    'productsproductKTRUcharacteristicscharacteristicsUsingReferenceInfovaluesvaluerangeSetvalueRangemax': 'Объекты_закуп_Характеристика_позиции_Максимальное_значение',
    'productsproductKTRUcharacteristicscharacteristicsUsingReferenceInfovaluesvaluerangeSetvalueRangemin': 'Объекты_закуп_Характеристика_позиции_Минимальное_значение',
    'productsproductKTRUcharacteristicscharacteristicsUsingTextFormname': 'Объекты_закуп_Характеристика_позиции',
    'productsproductKTRUcharacteristicscharacteristicsUsingTextFormvalueSetconcreteValue': 'Объекты_закуп_Характеристика_позиции_Значение',
    'productsproductKTRUcharacteristicscharacteristicsUsingTextFormvaluequalityDescription': 'Объекты_закуп_Характеристика_позиции_Описание',
    'productsproductKTRUname': 'Объекты_закуп_Классификация_по_КТРУ',
    'productsproductMNNInfoMNNName': 'Объекты_закуп_Наим_лекарств_препарата',
    'productsproductOKEIfullName': 'Объекты_закуп_Единица_измерения',
    'productsproductVATRate': 'Объекты_закуп_Ставка_НДС',
    'productsproductcharacteristicscharacteristicsUsingReferenceInfoname': 'Объекты_закуп_Характеристика_позиции',
    'productsproductcharacteristicscharacteristicsUsingReferenceInfovalueRangemax': 'Объекты_закуп_Характеристика_позиции_Максимальное_значение',
    'productsproductcharacteristicscharacteristicsUsingReferenceInfovalueRangemin': 'Объекты_закуп_Характеристика_позиции_Минимальное_значение',
    'productsproductcharacteristicscharacteristicsUsingReferenceInfovalueSetconcreteValue': 'Объекты_закуп_Характеристика_позиции_Значение',
    'productsproductcharacteristicscharacteristicsUsingReferenceInfovaluequalityDescription': 'Объекты_закуп_Характеристика_позиции_Описание',
    'productsproductcharacteristicscharacteristicsUsingReferenceInfovaluesvaluequalityDescription': 'Объекты_закуп_Характеристика_позиции_Описание',
    'productsproductcharacteristicscharacteristicsUsingTextFormname': 'Объекты_закуп_Характеристика_позиции',
    'productsproductcharacteristicscharacteristicsUsingTextFormvalueRangemax': 'Объекты_закуп_Характеристика_позиции_Максимальное_значение',
    'productsproductcharacteristicscharacteristicsUsingTextFormvalueRangemin': 'Объекты_закуп_Характеристика_позиции_Минимальное_значение',
    'productsproductcharacteristicscharacteristicsUsingTextFormvaluequalityDescription': 'Объекты_закуп_Характеристика_позиции_Описание',
    'productsproductdrugPurchaseObjectInfodrugInfoUsingReferenceInfoMNNsInfoMNNInfoMNNName': 'Объекты_закуп_Лекарственный_препарат_Наим_МНН',
    'productsproductdrugPurchaseObjectInfodrugInfoUsingReferenceInfoMNNsInfoMNNInfopositionsTradeNamepositionTradeNametradeInfotradeName': 'Объекты_закуп_Лекарственный_препарат_Торговое_наим',
    'productsproducthierarchyType': 'Объекты_закуп_Тип_обекта_закуп_в_иерархии',
    'productsproductimprovedProductReplacement': 'Объекты_закуп_Поставляется_обект_закуп_с_улучш_харками',
    'productsproductindexNum': 'Объекты_закуп_Номер',
    'productsproductmedicalProductInfomedicalProductName': 'Объекты_закуп_Медицинское_изделие_Наим',
    'productsproductname': 'Объекты_закуп_Назв',
    'productsproductpackagingInfocompleteness': 'Объекты_закуп_Комплектность_упаковки',
    'productsproductprice': 'Объекты_закуп_Цена_в_валют_кнтркта',
    'productsproductpriceRUR': 'Объекты_закуп_Цена_в_руб_экв',
    'productsproductquantity': 'Объекты_закуп_Колво',
    'productsproductsum': 'Объекты_закуп_Стоимость_в_валют_кнтркта',
    'productsproductsumRUR': 'Объекты_закуп_Стоимость_в_руб_экв',
    'productsproducttradeInfotradeName': 'Объекты_закуп_Торговое_наим_препарата',
    'productsproducttype': 'Объекты_закуп_Тип_обекта',
    'productsproductvalueRangemax': 'Объекты_закуп_Характеристика_позиции_Максимальное_значение',
    'productsproductvalueRangemin': 'Объекты_закуп_Характеристика_позиции_Минимальное_значение',
    'productsproductvalueSetconcreteValue': 'Объекты_закуп_Характеристика_позиции_Значение',
    'productsproductvaluequalityDescription': 'Объекты_закуп_Характеристика_позиции_Описание',
    'productsproductvolumeSpecifyingMethod': 'Объекты_закуп_Характеристика_позиции_Значение',
    'productsproductvolumeTextForm': 'Объекты_закуп_Характеристика_позиции_Значение',
    'protocolDate': 'Дата_подведения_результатов_определения_поставщ',
    'quantityContractStages': 'Количество_этапов_кнтркта',
    'receiptDocumentsattachmentdocDescription': 'Док_подтверждающие_приемку_товара_Описание',
    'receiptDocumentsattachmentfileName': 'Док_подтверждающие_приемку_товара_Назв',
    'receiptDocumentsattachmenturl': 'Док_подтверждающие_приемку_товара_Ссылка',
    'scanDocumentsattachmentdocDescription': 'Отсканированная_копия_кнтркта_Описание',
    'scanDocumentsattachmentfileName': 'Отсканированная_копия_кнтркта_Назв',
    'scanDocumentsattachmenturl': 'Отсканированная_копия_кнтркта_Ссылка',
    'signDate': 'Дата_заключ_кнтркта',
    'suppliersInfosupplierInfoEGRULInfoINN': 'Инфо_о_поставщ_Сведения_из_ЕГРЮЛ_ИНН',
    'suppliersInfosupplierInfoEGRULInfoKPP': 'Инфо_о_поставщ_Сведения_из_ЕГРЮЛ_КПП',
    'suppliersInfosupplierInfoEGRULInfoOGRN': 'Инфо_о_поставщ_Сведения_из_ЕГРЮЛ_ОГРН',
    'suppliersInfosupplierInfoEGRULInfoaddress': 'Инфо_о_поставщ_Сведения_из_ЕГРЮЛ_Адрес',
    'suppliersInfosupplierInfoEGRULInfofirmName': 'Инфо_о_поставщ_Сведения_из_ЕГРЮЛ_Фирменное_наим',
    'suppliersInfosupplierInfoEGRULInfofullName': 'Инфо_о_поставщ_Сведения_из_ЕГРЮЛ_Полное_наим',
    'suppliersInfosupplierInfoEGRULInforegistrationDate': 'Инфо_о_поставщ_Сведения_из_ЕГРЮЛ_Дата_постановки_на_учет',
    'suppliersInfosupplierInfoEGRULInfoshortName': 'Инфо_о_поставщ_Сведения_из_ЕГРЮЛ_Краткое_наим',
    'suppliersInfosupplierInfoOKTMOname': 'Инфо_о_поставщ_Код_терр_муниц_образования',
    'suppliersInfosupplierInfosupplierAccountsDetailssupplierAccountDetailsaccountType': 'Инфо_о_поставщ_Рекв_счета_поставщ_Тип_аккаунта',
    'suppliersInfosupplierInfosupplierAccountsDetailssupplierAccountDetailsbankAccountNumber': 'Инфо_о_поставщ_Рекв_счета_поставщ_Номер_банковского_счета',
    'suppliersInfosupplierInfosupplierAccountsDetailssupplierAccountDetailsbik': 'Инфо_о_поставщ_Рекв_счета_поставщ_БИК',
    'suppliersInfosupplierInfosupplierAccountsDetailssupplierAccountDetailscorrAccountNumber': 'Инфо_о_поставщ_Рекв_счета_поставщ_Коррсчет',
    'suppliersInfosupplierInfosupplierAccountsDetailssupplierAccountDetailscreditOrgName': 'Инфо_о_поставщ_Рекв_счета_поставщ_Наим_кредитной_организации',
    'supplierssupplierOKTMOname': 'Поставщики_Код_терр_муниц_образования',
    'terminationDocumentsattachmentdocDescription': 'Инфо_о_расторжении_кнтркта_Вложение_Описание',
    'terminationDocumentsattachmentfileName': 'Инфо_о_расторжении_кнтркта_Вложение_Назв',
    'terminationDocumentsattachmenturl': 'Инфо_о_расторжении_кнтркта_Вложение_Ссылка',
    'terminationdecisionDate': 'Инфо_о_расторжении_кнтркта_Дата_уведомления',
    'terminationdocTerminationdocumentDate': 'Инфо_о_расторжении_кнтркта_Основан_расторжения_кнтркта_Дата',
    'terminationdocTerminationdocumentNum': 'Инфо_о_расторжении_кнтркта_Основан_расторжения_кнтркта_Номер',
    'terminationdocTerminationname': 'Инфо_о_расторжении_кнтркта_Основан_расторжения_кнтркта_Назв',
    'terminationpaid': 'Инфо_о_расторжении_кнтркта_Фактически_оплачено',
    'terminationreasonInfo': 'Инфо_о_расторжении_кнтркта_Причина_расторжения_кнтркта',
    'terminationreasonname': 'Инфо_о_расторжении_кнтркта_Основан_расторжения_кнтркта',
    'terminationterminationDate': 'Инфо_о_расторжении_кнтркта_Дата_расторжения_кнтркта',
    'archive_name': 'Название_архива'}  # Импортируемые строки в БД
columns = [
    'id',
    'regNum',
    'publish_date',
    'Регион',
    'Печатная_форма_кнтркта',
    'Текущее_состояние_кнтркта',
    'Номер_кнтркта',
    'Номер_изменения',
    'Прикрепленный_док_Описание',
    'Прикрепленный_док_Назв',
    'Прикрепленный_док_Ссылка',
    'Предмет_кнтркта',
    'Рекв_счета_заказчика_Тип_счета',
    'Рекв_счета_заказчика_Номер_счета',
    'Рекв_счета_заказчика_БИК_банка',
    'Рекв_счета_заказчика_Корр_счет',
    'Рекв_счета_заказчика_Наим_банка',
    'Заказчик_Полное_наим',
    'Заказчик_ИНН',
    'Заказчик_КПП',
    'Заказчик_Дата_постановки_на_учет',
    'Заказчик_Сокращенное_наим',
    'Место_поставки_Назв',
    'Место_поставки_Адрес',
    'Рекв_дока_подтверждающего_основание_заключ_кнтркта',
    'Дата_окончания_исполнения_кнтркта',
    'Дата_окончания_исполнения_этапа',
    'Размер_аванса_по_этапу_кнтркта_в_валют_кнтркта',
    'Размер_аванса_по_этапу_кнтркта_в_российских_рублях',
    'Процент_аванса_по_этапу_кнтркта',
    'Цена_этапа_кнтркта_в_валют_кнтркта',
    'Цена_этапа_кнтркта_в_российских_рублях',
    'Дата_начала_исполнения_этапа',
    'Дата_начала_исполнения_кнтркта',
    'Инфо_об_исполн_Имя_по_КТРУ',
    'Инфо_об_исполн_Предмет_кнтркта_наим_лекарств_препаратов',
    'Инфо_об_исполн_Единица_измерения',
    'Инфо_об_исполн_Классификация_по_ОКПД2',
    'Инфо_об_исполн_Прикрепленный_док_Описание',
    'Инфо_об_исполн_Прикрепленный_док_Назв',
    'Инфо_об_исполн_Прикрепленный_док_Ссылка',
    'Инфо_об_исполн_Валюта',
    'Инфо_об_исполн_Док_о_приемке_Дата_подписания_заказчиком',
    'Инфо_об_исполн_Док_о_приемке_Дата',
    'Инфо_об_исполн_Док_о_приемке_Номер',
    'Инфо_об_исполн_Док_о_приемке_Стоимость_исполненных_обязательств',
    'Инфо_об_исполн_Док_о_приемке_Назв',
    'Инфо_об_исполн_Док_подтверждающий_приемку_товара_Описание',
    'Инфо_об_исполн_Док_подтверждающий_приемку_товара_Назв',
    'Инфо_об_исполн_Док_подтверждающий_приемку_товара_Ссылка',
    'Инфо_об_исполн_Док_об_исполн_кнтркта_Дата',
    'Инфо_об_исполн_Док_об_исполн_кнтркта_Номер',
    'Инфо_об_исполн_Док_об_исполн_кнтркта_Назв',
    'Инфо_об_исполн_Фактически_оплачено_в_валюте_платежа',
    'Инфо_об_исполн_Фактически_оплачено_в_руб_экв',
    'Инфо_об_исполн_Значение_НДС_факт_оплач_суммы_в_валюте_платежа',
    'Инфо_об_исполн_Значение_НДС_факт_оплач_суммы_в_руб_экв',
    'Инфо_об_исполн_Платежный_док_Дата',
    'Инфо_об_исполн_Платежный_док_Назв',
    'Инфо_об_исполн_Платежный_док_Номер',
    'Инфо_об_исполн_Объект_закуп_Ставка_НДС',
    'Инфо_об_исполн_Объект_закуп_Назв',
    'Инфо_об_исполн_Объект_закуп_Колво',
    'Инфо_об_исполн_Объект_закуп_Тип',
    'Инфо_об_исполн_Инфо_об_обекте_закуп_Стоимость',
    'Инфо_об_исполн_Инфо_об_обекте_закуп_Порядковый_номер',
    'Инфо_об_исполн_Инфо_об_обекте_закуп_Описание',
    'Инфо_об_исполн_Инфо_об_обекте_закуп_Колво',
    'Инфо_об_исполн_Инфо_об_обекте_закуп_Назв_по_КТРУ',
    'Инфо_об_исполн_Инфо_об_обекте_закуп_Единица_измерения',
    'Инфо_об_исполн_Инфо_об_обекте_закуп_Назв_по_ОКПД2',
    'Инфо_об_исполн_Инфо_об_обекте_закуп_Ставка_НДС',
    'Инфо_об_исполн_Инфо_об_обекте_закуп_Тип_обекта_закуп_в_иерархии',
    'Инфо_об_исполн_Инфо_об_обекте_закуп_Назв',
    'Инфо_об_исполн_Инфо_об_обекте_закуп_Объем_ранее_поставленного',
    'Инфо_об_исполн_Инфо_об_обекте_закуп_Тип',
    'Инфо_об_исполн_Инфо_об_обекте_закуп_Цена',
    'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_НДС',
    'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Ставка_НДС',
    'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Колво_упаковок',
    'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Серия',
    'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Срок_годности',
    'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Стоимость',
    'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Стоимость_ЖНВЛП',
    'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Цена_упаковки',
    'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Наим_МНН',
    'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Единица_измерения',
    'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Назв_по_ОКПД2',
    'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Торговое_назв',
    'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Назв',
    'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Колво',
    'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Тип',
    'Инфо_об_исполн_Инфо_об_обекте_мед_закуп_Колво_поставленного',
    'Инфо_об_исполн_Док_подтверждающие_приемку_товара_Описание',
    'Инфо_об_исполн_Док_подтверждающие_приемку_товара_Назв',
    'Инфо_об_исполн_Док_подтверждающие_приемку_товара_Ссылка',
    'Инфо_об_исполн_Номер_исполнения_в_рамках_этапа',
    'Инфо_об_исполн_Дата_окончания_исполнения_этапа',
    'Основан_заключ_кнтркта_Закуп_Реестровый_номер',
    'Основан_заключ_кнтркта_Закуп_Порядковый_номер_лота',
    'Основан_заключ_кнтркта_Закуп_Номер_извещения_о_проведении',
    'Основан_заключ_кнтркта_Закуп_Способ_определения_поставщиков',
    'Основан_заключ_кнтркта_Закуп_у_одного_поставщ_Вложение_Описание',
    'Основан_заключ_кнтркта_Закуп_у_одного_поставщ_Вложение_Назв',
    'Основан_заключ_кнтркта_Закуп_у_одного_поставщ_Вложение_Ссылка',
    'Основан_заключ_кнтркта_Закуп_у_одного_поставщ_Док',
    'Основан_заключ_кнтркта_Закуп_у_одного_поставщ_Причина',
    'Основан_заключ_кнтркта_Закуп_у_един_поставщ_Вложение_Описание',
    'Основан_заключ_кнтркта_Закуп_у_един_поставщ_Вложение_Назв',
    'Основан_заключ_кнтркта_Закуп_у_един_поставщ_Вложение_Ссылка',
    'Основан_заключ_кнтркта_Закуп_у_един_поставщ_Док',
    'Основан_заключ_кнтркта_Закуп_у_един_поставщ_Причина',
    'Гиперссылка_на_опубликованные_сведения_о_контракте',
    'Док_подтверждающие_исполнение_оплату_Вложение_Описание',
    'Док_подтверждающие_исполнение_оплату_Вложение_Назв',
    'Док_подтверждающие_исполнение_оплату_Вложение_Ссылка',
    'Инфо_о_неустойках_Начисл_неуст_Размер',
    'Инфо_о_неустойках_Начисл_неуст_Сторона_кнтркта',
    'Инфо_о_неустойках_Начисл_неуст_Валюта',
    'Инфо_о_неустойках_Начисл_неуст_Оплата_Сумма_в_валюте',
    'Инфо_о_неустойках_Начисл_неуст_Оплата_Сумма_в_рублях',
    'Инфо_о_неустойках_Начисл_неуст_Докуент_об_оплате_Дата',
    'Инфо_о_неустойках_Начисл_неуст_Докуент_об_оплате_Назв',
    'Инфо_о_неустойках_Начисл_неуст_Докуент_об_оплате_Номер',
    'Инфо_о_неустойках_Начисл_неуст_Итого_оплачено',
    'Инфо_о_неустойках_Начисл_неуст_Требование_заказчика_Дата',
    'Инфо_о_неустойках_Начисл_неуст_Требование_заказчика_Назв',
    'Инфо_о_неустойках_Начисл_неуст_Требование_заказчика_Номер',
    'Инфо_о_неустойках_Начисл_неуст_Причина',
    'Инфо_о_неустойках_Начисл_неуст_Тип_взыскания',
    'Дата_первоначального_размещения_дока',
    'Организация_разместившая_контракт',
    'Роль_организации_разместившей_контракт',
    'Инфо_о_цене_кнтркта_Валюта',
    'Инфо_о_цене_кнтркта_Цена_в_валют_кнтркта',
    'Инфо_о_цене_кнтркта_Цена_кнтркта_в_руб_экв',
    'Инфо_о_цене_кнтркта_Значение_НДС_в_валют_кнтркта',
    'Инфо_о_цене_кнтркта_Значение_НДС_в_руб_экв',
    'Объекты_закуп_Характеристика_позиции',
    'Объекты_закуп_Характеристика_позиции_Максимальное_значение',
    'Объекты_закуп_Характеристика_позиции_Минимальное_значение',
    'Объекты_закуп_Характеристика_позиции_Значение',
    'Объекты_закуп_Характеристика_позиции_Описание',
    'Объекты_закуп_Классификация_по_КТРУ',
    'Объекты_закуп_Наим_лекарств_препарата',
    'Объекты_закуп_Единица_измерения',
    'Объекты_закуп_Ставка_НДС',
    'Объекты_закуп_Лекарственный_препарат_Наим_МНН',
    'Объекты_закуп_Лекарственный_препарат_Торговое_наим',
    'Объекты_закуп_Тип_обекта_закуп_в_иерархии',
    'Объекты_закуп_Поставляется_обект_закуп_с_улучш_харками',
    'Объекты_закуп_Номер',
    'Объекты_закуп_Медицинское_изделие_Наим',
    'Объекты_закуп_Назв',
    'Объекты_закуп_Комплектность_упаковки',
    'Объекты_закуп_Цена_в_валют_кнтркта',
    'Объекты_закуп_Цена_в_руб_экв',
    'Объекты_закуп_Колво',
    'Объекты_закуп_Стоимость_в_валют_кнтркта',
    'Объекты_закуп_Стоимость_в_руб_экв',
    'Объекты_закуп_Торговое_наим_препарата',
    'Объекты_закуп_Тип_обекта',
    'Дата_подведения_результатов_определения_поставщ',
    'Количество_этапов_кнтркта',
    'Док_подтверждающие_приемку_товара_Описание',
    'Док_подтверждающие_приемку_товара_Назв',
    'Док_подтверждающие_приемку_товара_Ссылка',
    'Отсканированная_копия_кнтркта_Описание',
    'Отсканированная_копия_кнтркта_Назв',
    'Отсканированная_копия_кнтркта_Ссылка',
    'Дата_заключ_кнтркта',
    'Инфо_о_поставщ_Сведения_из_ЕГРЮЛ_ИНН',
    'Инфо_о_поставщ_Сведения_из_ЕГРЮЛ_КПП',
    'Инфо_о_поставщ_Сведения_из_ЕГРЮЛ_ОГРН',
    'Инфо_о_поставщ_Сведения_из_ЕГРЮЛ_Адрес',
    'Инфо_о_поставщ_Сведения_из_ЕГРЮЛ_Фирменное_наим',
    'Инфо_о_поставщ_Сведения_из_ЕГРЮЛ_Полное_наим',
    'Инфо_о_поставщ_Сведения_из_ЕГРЮЛ_Дата_постановки_на_учет',
    'Инфо_о_поставщ_Сведения_из_ЕГРЮЛ_Краткое_наим',
    'Инфо_о_поставщ_Код_терр_муниц_образования',
    'Инфо_о_поставщ_Рекв_счета_поставщ_Тип_аккаунта',
    'Инфо_о_поставщ_Рекв_счета_поставщ_Номер_банковского_счета',
    'Инфо_о_поставщ_Рекв_счета_поставщ_БИК',
    'Инфо_о_поставщ_Рекв_счета_поставщ_Коррсчет',
    'Инфо_о_поставщ_Рекв_счета_поставщ_Наим_кредитной_организации',
    'Поставщики_Код_терр_муниц_образования',
    'Инфо_о_расторжении_кнтркта_Вложение_Описание',
    'Инфо_о_расторжении_кнтркта_Вложение_Назв',
    'Инфо_о_расторжении_кнтркта_Вложение_Ссылка',
    'Инфо_о_расторжении_кнтркта_Дата_уведомления',
    'Инфо_о_расторжении_кнтркта_Основан_расторжения_кнтркта_Дата',
    'Инфо_о_расторжении_кнтркта_Основан_расторжения_кнтркта_Номер',
    'Инфо_о_расторжении_кнтркта_Основан_расторжения_кнтркта_Назв',
    'Инфо_о_расторжении_кнтркта_Фактически_оплачено',
    'Инфо_о_расторжении_кнтркта_Причина_расторжения_кнтркта',
    'Инфо_о_расторжении_кнтркта_Основан_расторжения_кнтркта',
    'Инфо_о_расторжении_кнтркта_Дата_расторжения_кнтркта',
    'Название_архива']      # Наименования столбцов в таблицах БД
direction = '/home/parser/contracts_new/'  # Рабочая директория
# direction = ''


def regions(code):
    """Имена регионов, соответственно его коду
    :param code: Код региона
    :return: Возвращает имя региона или 0, если регион не найден"""
    return region.get(code, 0)


def table_name(region):
    """Функция определения названия таблицы по номеру региона
    :param region: Код региона
    :return: Возвращает название таблицы"""
    if region in ['78', '47', '53', '60', '10', '29', '11', '35', '51', '83', '39']:
        return 'northwestern_fd'
    if region in ['32', '33', '37', '40', '44', '57', '62', '67', '69', '71', '76', '31', '36', '46', '48', '68']:
        return 'central_fd'
    if region in ['52', '43', '12', '13', '21', '58', '73', '64', '63', '56', '02', '16', '18', '59']:
        return 'volga_fd'
    if region in ['08', '34', '30', '01', '61', '23']:
        return 'southern_fd'
    if region in ['26', '15', '09', '07', '20', '06', '05']:
        return 'north_caucasian_fd'
    if region in ['66', '74', '45', '72', '89', '86']:
        return 'ural_fd'
    if region in ['04', '22', '54', '70', '42', '55', '19', '17', '24', '38', '03', '75']:
        return 'siberian_fd'
    if region in ['14', '79', '87', '25', '27', '28', '41', '49', '65']:
        return 'far_eastern_fd'
    if region in ['77', '50']:
        return 'moscow_and_moscow_region'
    return 'crimean_fd'
